version: '3'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src 
      - /app/build
      - ./node_modules:/app/node_modules
      - ./nodemon.json:/app/nodemon.json 
    depends_on:
      - cassandra

  cassandra:
    image: cassandra:latest
    ports:
      - 9042:9042
    volumes:
      - ./cassandra-data:/var/lib/cassandra/data
